### ISSUE TITLE
Can't access the Kibana Dashboard file in the docs

### ISSUE THREAD

**Issue by jivinivan** [aws-samples/amazon-transcribe-comprehend-podcast#2]
![image](https://user-images.githubusercontent.com/1165669/66569985-aaf00d00-eb3a-11e9-8f4b-c0618000b9e5.png)

Access is denied for this file: https://angelaw-workshop.s3.amazonaws.com/kibana.json

**Comment by angelarw** [comment]
Sorry about that! can you try again? should be accessible now

**Comment by jivinivan** [comment]
It works now, thanks!
