### ISSUE TITLE
Getting errors while trying to deploy the template

### ISSUE THREAD

**Issue by gulshanmehta** [aws-samples/amazon-transcribe-comprehend-podcast#7]
Getting below issues while trying to deploy this cloudformation stack

2020-04-05 15:40:58 UTC+0530	ESDomain	
CREATE_FAILED	Domain needs to be specified for user pool (Service: AWSElasticsearch; Status Code: 400; Error Code: ValidationException; Request ID: 3a6f250c-5d94-46d2-bbff-9f09d21f6393)

2020-04-05 15:40:59 UTC+0530	podcast-transcribe-index	
ROLLBACK_IN_PROGRESS	The following resource(s) failed to create: [CognitoAuthKibanaPolicy, ESDomain]. . Rollback requested by user.
2020-04-05 15:40:58 UTC+0530	CognitoAuthKibanaPolicy	
CREATE_FAILED	Resource creation cancelled

any suggestions what could the issues?

**Comment by angelarw** [comment]
sorry about that. can you delete the stack and try again? i think i have fixed the issue

**Comment by gulshanmehta** [comment]
able to deploy the cloudformation template successfully now..thanks
